In [1]:
# Importing the necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
ls

Car_price_predictions.ipynb  Data_Train.xlsx  Sample_submission.xlsx
Data_Test.xlsx               README.md


In [54]:
# Loading our file into a data frame
df = pd.read_excel('Data_Train.xlsx')   # For the training set
df2 = pd.read_excel('Data_Test.xlsx')   # For the testing set

In [55]:
df.head()  

Name    Location  Year  Kilometers_Driven  \
0            Maruti Wagon R LXI CNG      Mumbai  2010              72000   
1  Hyundai Creta 1.6 CRDi SX Option        Pune  2015              41000   
2                      Honda Jazz V     Chennai  2011              46000   
3                 Maruti Ertiga VDI     Chennai  2012              87000   
4   Audi A4 New 2.0 TDI Multitronic  Coimbatore  2013              40670   

  Fuel_Type Transmission Owner_Type     Mileage   Engine      Power  Seats  \
0       CNG       Manual      First  26.6 km/kg   998 CC  58.16 bhp    5.0   
1    Diesel       Manual      First  19.67 kmpl  1582 CC  126.2 bhp    5.0   
2    Petrol       Manual      First   18.2 kmpl  1199 CC   88.7 bhp    5.0   
3    Diesel       Manual      First  20.77 kmpl  1248 CC  88.76 bhp    7.0   
4    Diesel    Automatic     Second   15.2 kmpl  1968 CC  140.8 bhp    5.0   

   New_Price  Price  
0        NaN   1.75  
1        NaN  12.50  
2  8.61 Lakh   4.50  
3        NaN   6.00  
4        NaN  17.74

In [56]:
df2.head()

Name    Location  Year  \
0                    Maruti Alto K10 LXI CNG       Delhi  2014   
1              Maruti Alto 800 2016-2019 LXI  Coimbatore  2013   
2  Toyota Innova Crysta Touring Sport 2.4 MT      Mumbai  2017   
3                       Toyota Etios Liva GD   Hyderabad  2012   
4                          Hyundai i20 Magna      Mumbai  2014   

   Kilometers_Driven Fuel_Type Transmission Owner_Type      Mileage   Engine  \
0              40929       CNG       Manual      First  32.26 km/kg   998 CC   
1              54493    Petrol       Manual     Second    24.7 kmpl   796 CC   
2              34000    Diesel       Manual      First   13.68 kmpl  2393 CC   
3             139000    Diesel       Manual      First   23.59 kmpl  1364 CC   
4              29000    Petrol       Manual      First    18.5 kmpl  1197 CC   

       Power  Seats   New_Price  
0   58.2 bhp    4.0         NaN  
1   47.3 bhp    5.0         NaN  
2  147.8 bhp    7.0  25.27 Lakh  
3   null bhp    5.0         NaN  
4  82.85 bhp    5.0         NaN

In [57]:
# Cleaning our Train data
df['Engine'] = df['Engine'].str.replace('CC', '')
df['Power'] = df['Power'].str.replace('bhp', '')
df['Mileage'] = df['Mileage'].str.replace('km/kg', '')
df['Mileage'] = df['Mileage'].str.replace('kmpl', '')
df['Power'] = df['Power'].str.replace('null', 'NaN')
df['New_Price'] = df['New_Price'].str.replace('Lakh', '') # New_Price

# Cleaning our Test data
df2['Engine'] = df2['Engine'].str.replace('CC', '')
df2['Power'] = df2['Power'].str.replace('bhp', '')
df2['Mileage'] = df2['Mileage'].str.replace('km/kg', '')
df2['Mileage'] = df2['Mileage'].str.replace('kmpl', '')
df2['Power'] = df2['Power'].str.replace('null', 'NaN')
df2['New_Price'] = df2['New_Price'].str.replace('Lakh','')  # New_Price
df2.head()
# df.Mileage = [x.strip('km/kg') for x in df.Mileage]
# dataset.info()
df2.head()

Name    Location  Year  \
0                    Maruti Alto K10 LXI CNG       Delhi  2014   
1              Maruti Alto 800 2016-2019 LXI  Coimbatore  2013   
2  Toyota Innova Crysta Touring Sport 2.4 MT      Mumbai  2017   
3                       Toyota Etios Liva GD   Hyderabad  2012   
4                          Hyundai i20 Magna      Mumbai  2014   

   Kilometers_Driven Fuel_Type Transmission Owner_Type Mileage Engine   Power  \
0              40929       CNG       Manual      First  32.26    998    58.2    
1              54493    Petrol       Manual     Second   24.7    796    47.3    
2              34000    Diesel       Manual      First  13.68   2393   147.8    
3             139000    Diesel       Manual      First  23.59   1364     NaN    
4              29000    Petrol       Manual      First   18.5   1197   82.85    

   Seats New_Price  
0    4.0       NaN  
1    5.0       NaN  
2    7.0    25.27   
3    5.0       NaN  
4    5.0       NaN

In [58]:
df.head()

Name    Location  Year  Kilometers_Driven  \
0            Maruti Wagon R LXI CNG      Mumbai  2010              72000   
1  Hyundai Creta 1.6 CRDi SX Option        Pune  2015              41000   
2                      Honda Jazz V     Chennai  2011              46000   
3                 Maruti Ertiga VDI     Chennai  2012              87000   
4   Audi A4 New 2.0 TDI Multitronic  Coimbatore  2013              40670   

  Fuel_Type Transmission Owner_Type Mileage Engine   Power  Seats New_Price  \
0       CNG       Manual      First   26.6    998   58.16     5.0       NaN   
1    Diesel       Manual      First  19.67   1582   126.2     5.0       NaN   
2    Petrol       Manual      First   18.2   1199    88.7     5.0     8.61    
3    Diesel       Manual      First  20.77   1248   88.76     7.0       NaN   
4    Diesel    Automatic     Second   15.2   1968   140.8     5.0       NaN   

   Price  
0   1.75  
1  12.50  
2   4.50  
3   6.00  
4  17.74

In [59]:
df.describe()

Year  Kilometers_Driven        Seats        Price
count  6019.000000       6.019000e+03  5977.000000  6019.000000
mean   2013.358199       5.873838e+04     5.278735     9.479468
std       3.269742       9.126884e+04     0.808840    11.187917
min    1998.000000       1.710000e+02     0.000000     0.440000
25%    2011.000000       3.400000e+04     5.000000     3.500000
50%    2014.000000       5.300000e+04     5.000000     5.640000
75%    2016.000000       7.300000e+04     5.000000     9.950000
max    2019.000000       6.500000e+06    10.000000   160.000000

In [60]:
# Dropping columns Name and New_Price
df.drop(['Name', 'New_Price'], axis = 1, inplace = True)
df2.drop(['Name', 'New_Price'], axis = 1, inplace = True)

In [61]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6019 entries, 0 to 6018
Data columns (total 11 columns):
Location             6019 non-null object
Year                 6019 non-null int64
Kilometers_Driven    6019 non-null int64
Fuel_Type            6019 non-null object
Transmission         6019 non-null object
Owner_Type           6019 non-null object
Mileage              6017 non-null object
Engine               5983 non-null object
Power                5983 non-null object
Seats                5977 non-null float64
Price                6019 non-null float64
dtypes: float64(2), int64(2), object(7)
memory usage: 517.3+ KB


In [62]:
df.isnull().sum()  # Calculating the null values in our dataset

Location              0
Year                  0
Kilometers_Driven     0
Fuel_Type             0
Transmission          0
Owner_Type            0
Mileage               2
Engine               36
Power                36
Seats                42
Price                 0
dtype: int64

In [63]:
df2.isnull().sum()

Location              0
Year                  0
Kilometers_Driven     0
Fuel_Type             0
Transmission          0
Owner_Type            0
Mileage               0
Engine               10
Power                10
Seats                11
dtype: int64

In [64]:
df.head()

Location  Year  Kilometers_Driven Fuel_Type Transmission Owner_Type  \
0      Mumbai  2010              72000       CNG       Manual      First   
1        Pune  2015              41000    Diesel       Manual      First   
2     Chennai  2011              46000    Petrol       Manual      First   
3     Chennai  2012              87000    Diesel       Manual      First   
4  Coimbatore  2013              40670    Diesel    Automatic     Second   

  Mileage Engine   Power  Seats  Price  
0   26.6    998   58.16     5.0   1.75  
1  19.67   1582   126.2     5.0  12.50  
2   18.2   1199    88.7     5.0   4.50  
3  20.77   1248   88.76     7.0   6.00  
4   15.2   1968   140.8     5.0  17.74

In [65]:
df2.head()

Location  Year  Kilometers_Driven Fuel_Type Transmission Owner_Type  \
0       Delhi  2014              40929       CNG       Manual      First   
1  Coimbatore  2013              54493    Petrol       Manual     Second   
2      Mumbai  2017              34000    Diesel       Manual      First   
3   Hyderabad  2012             139000    Diesel       Manual      First   
4      Mumbai  2014              29000    Petrol       Manual      First   

  Mileage Engine   Power  Seats  
0  32.26    998    58.2     4.0  
1   24.7    796    47.3     5.0  
2  13.68   2393   147.8     7.0  
3  23.59   1364     NaN     5.0  
4   18.5   1197   82.85     5.0

In [66]:
# Splitting our data into dependent and independent variables for training set
y = df.iloc[:, 10].values
X = df.iloc[:, :10].values
df.drop('Price', axis = 1, inplace = True)
df.head()

X2 = df2.iloc[:, :10].values  # Testing Data assigned to dependent variable

In [67]:
X

array([['Mumbai', 2010, 72000, ..., '998 ', '58.16 ', 5.0],
       ['Pune', 2015, 41000, ..., '1582 ', '126.2 ', 5.0],
       ['Chennai', 2011, 46000, ..., '1199 ', '88.7 ', 5.0],
       ...,
       ['Jaipur', 2012, 55000, ..., '2498 ', '112 ', 8.0],
       ['Kolkata', 2013, 46000, ..., '998 ', '67.1 ', 5.0],
       ['Hyderabad', 2011, 47000, ..., '936 ', '57.6 ', 5.0]],
      dtype=object)

In [68]:
X2

array([['Delhi', 2014, 40929, ..., '998 ', '58.2 ', 4.0],
       ['Coimbatore', 2013, 54493, ..., '796 ', '47.3 ', 5.0],
       ['Mumbai', 2017, 34000, ..., '2393 ', '147.8 ', 7.0],
       ...,
       ['Kolkata', 2012, 28000, ..., '1461 ', '63.1 ', 5.0],
       ['Pune', 2013, 52262, ..., '1197 ', '103.6 ', 5.0],
       ['Kochi', 2014, 72443, ..., '2148 ', '170 ', 5.0]], dtype=object)

In [833]:
X[:, :10]

array([[2010, 72000, '26.6 ', ..., 0, 0, 0],
       [2015, 41000, '19.67 ', ..., 0, 0, 0],
       [2011, 46000, '18.2 ', ..., 0, 1, 0],
       ...,
       [2012, 55000, '14.0 ', ..., 0, 0, 0],
       [2013, 46000, '18.9 ', ..., 0, 0, 0],
       [2011, 47000, '25.44 ', ..., 0, 0, 0]], dtype=object)

In [834]:
X[2]

array([2011, 46000, '18.2 ', '1199 ', '88.7 ', 5.0, 0, 0, 1, 0],
      dtype=object)

In [19]:
# Mark empty values as missing or NaN
df[['Mileage', 'Engine', 'Power', 'Seats']] = df[['Mileage','Engine','Power', 'Seats']].replace('', np.NaN)
df2[['Mileage', 'Engine', 'Power', 'Seats']] = df2[['Mileage','Engine','Power', 'Seats']].replace('', np.NaN)

In [20]:
df['train'] = 1
df2['train'] = 0
combined = pd.concat((df, df2))  # Combining the DataFrames
s1 = ['Fuel_Type', 'Transmission', 'Owner_Type', 'Location']
new_df = pd.get_dummies(combined[s1])
# new_df = pd.get_dummies(combined['Fuel_Type'])
# new_df = pd.get_dummies(combined['Transmission'])
# new_df = pd.get_dummies(combined['Owner_Type'])


In [21]:
new_df.head()
# combined.head()

Fuel_Type_CNG  Fuel_Type_Diesel  Fuel_Type_Electric  Fuel_Type_LPG  \
0              1                 0                   0              0   
1              0                 1                   0              0   
2              0                 0                   0              0   
3              0                 1                   0              0   
4              0                 1                   0              0   

   Fuel_Type_Petrol  Transmission_Automatic  Transmission_Manual  \
0                 0                       0                    1   
1                 0                       0                    1   
2                 1                       0                    1   
3                 0                       0                    1   
4                 0                       1                    0   

   Owner_Type_First  Owner_Type_Fourth & Above  Owner_Type_Second  ...  \
0                 1                          0                  0  ...   
1                 1                          0                  0  ...   
2                 1                          0                  0  ...   
3                 1                          0                  0  ...   
4                 0                          0                  1  ...   

   Location_Bangalore  Location_Chennai  Location_Coimbatore  Location_Delhi  \
0                   0                 0                    0               0   
1                   0                 0                    0               0   
2                   0                 1                    0               0   
3                   0                 1                    0               0   
4                   0                 0                    1               0   

   Location_Hyderabad  Location_Jaipur  Location_Kochi  Location_Kolkata  \
0                   0                0               0                 0   
1                   0                0               0                 0   
2                   0                0               0                 0   
3                   0                0               0                 0   
4                   0                0               0                 0   

   Location_Mumbai  Location_Pune  
0                1              0  
1                0              1  
2                0              0  
3                0              0  
4                0              0  

[5 rows x 22 columns]

In [22]:
combined = pd.concat([combined, new_df], axis = 1)
train_df = combined[combined['train'] == 1]
test_df = combined[combined['train'] == 0]
s1 = ['Fuel_Type', 'Transmission', 'Owner_Type', 'Location', 'train']
train_df.drop(s1, axis = 1, inplace = True)
test_df.drop(s1, axis = 1, inplace = True)
test_df.head()

Year  Kilometers_Driven Mileage Engine   Power  Seats  Fuel_Type_CNG  \
0  2014              40929  32.26    998    58.2     4.0              1   
1  2013              54493   24.7    796    47.3     5.0              0   
2  2017              34000  13.68   2393   147.8     7.0              0   
3  2012             139000  23.59   1364     NaN     5.0              0   
4  2014              29000   18.5   1197   82.85     5.0              0   

   Fuel_Type_Diesel  Fuel_Type_Electric  Fuel_Type_LPG  ...  \
0                 0                   0              0  ...   
1                 0                   0              0  ...   
2                 1                   0              0  ...   
3                 1                   0              0  ...   
4                 0                   0              0  ...   

   Location_Bangalore  Location_Chennai  Location_Coimbatore  Location_Delhi  \
0                   0                 0                    0               1   
1                   0                 0                    1               0   
2                   0                 0                    0               0   
3                   0                 0                    0               0   
4                   0                 0                    0               0   

   Location_Hyderabad  Location_Jaipur  Location_Kochi  Location_Kolkata  \
0                   0                0               0                 0   
1                   0                0               0                 0   
2                   0                0               0                 0   
3                   1                0               0                 0   
4                   0                0               0                 0   

   Location_Mumbai  Location_Pune  
0                0              0  
1                0              0  
2                1              0  
3                0              0  
4                1              0  

[5 rows x 28 columns]

In [27]:
train_df.head()
X = train_df.iloc[:,:].values
X2 = test_df.iloc[:,:].values

In [29]:
# Replacing missing values with the mean of the columns
from sklearn.preprocessing import Imputer
imputer = Imputer(missing_values = 'NaN', strategy = 'mean', axis = 0)
imputer = imputer.fit(X[:, 2:])
X[:, 2:] = imputer.transform(X[:, 2:])

imputer = imputer.fit(X2[:, 2:])
X2[:, 2:] = imputer.transform(X2[:, 2:])

/home/afroz/anaconda3/lib/python3.7/site-packages/sklearn/utils/deprecation.py:58: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


In [30]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [61]:
from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor(n_estimators = 175, criterion = 'mse', random_state = 0)
model.fit(X_train, y_train)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=175, n_jobs=None,
           oob_score=False, random_state=0, verbose=0, warm_start=False)

In [62]:
y_pred = model.predict(X_test)
y_pred

array([7.92582857, 3.17211429, 3.96251429, ..., 7.60005714, 5.95211429,
       3.53468571])

In [63]:
y_test

array([7.25, 4.25, 3.9 , ..., 8.5 , 6.25, 3.87])

In [64]:
from sklearn import metrics  
print("MAE", metrics.mean_absolute_error(y_test, y_pred))
print("MSE", metrics.mean_squared_error(y_test, y_pred))
print("RMSE", np.sqrt(metrics.mean_squared_error(y_test, y_pred)))
print("Score:", model.score(X_test, y_test))

MAE 1.5243176626663952
MSE 11.507000313512746
RMSE 3.3921969744566347
Score: 0.9040115227029537


In [65]:
y_pred2 = model.predict(X2)

In [66]:
y_pred2

array([ 3.3344    ,  2.88125714, 17.0676    , ...,  3.11874286,
        4.68502857, 16.52974286])

In [67]:
output = np.column_stack((y_pred2))

In [325]:
df_results = pd.DataFrame??

In [68]:
df_results = pd.DataFrame(y_pred2, columns = ['Price'])
df_results.to_excel('car_price_results_1.xlsx', index = False)
# prediction ends
df_results


Price
0      3.334400
1      2.881257
2     17.067600
3      4.418171
4      4.508286
5     12.577829
6     21.406629
7      2.100171
8      3.716629
9     10.334800
10    17.018629
11     4.546171
12     2.408057
13     3.030229
14     5.042971
15    18.554914
16    30.058171
17     1.962686
18     7.860571
19     5.221600
20     4.241371
21     2.407257
22     3.570686
23     3.616571
24     4.929943
25     1.094743
26     1.359371
27     6.609257
28     6.213886
29     3.058857
...         ...
1204   6.205657
1205   3.506571
1206   5.642171
1207   2.907371
1208   1.685771
1209   4.012686
1210   3.483200
1211   4.245257
1212   8.486171
1213  14.881143
1214  19.481429
1215   5.065657
1216   9.322914
1217   6.586629
1218   3.372857
1219  15.487771
1220   5.093257
1221   9.504229
1222  21.983943
1223   3.739771
1224   6.394800
1225   1.841371
1226   4.969943
1227   6.325657
1228   3.790800
1229   3.972857
1230   6.310600
1231   3.118743
1232   4.685029
1233  16.529743

[1234 rows x 1 columns]

In [593]:
ls

car_price_results.xlsx  Data_Train.xlsx         Untitled.ipynb
Data_Test.xlsx          Sample_submission.xlsx


In [611]:
df2 = pd.read_excel('Data_Test.xlsx')

In [612]:
df2.drop(['Name', 'New_Price'], axis = 1, inplace = True)

In [637]:
df2.head()

Location  Year  Kilometers_Driven Fuel_Type Transmission Owner_Type  \
0       Delhi  2014              40929       CNG       Manual      First   
1  Coimbatore  2013              54493    Petrol       Manual     Second   
2      Mumbai  2017              34000    Diesel       Manual      First   
3   Hyderabad  2012             139000    Diesel       Manual      First   
4      Mumbai  2014              29000    Petrol       Manual      First   

  Mileage Engine   Power  Seats  
0  32.26    998    58.2     4.0  
1   24.7    796    47.3     5.0  
2  13.68   2393   147.8     7.0  
3  23.59   1364     NaN     5.0  
4   18.5   1197   82.85     5.0

In [614]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1234 entries, 0 to 1233
Data columns (total 10 columns):
Location             1234 non-null object
Year                 1234 non-null int64
Kilometers_Driven    1234 non-null int64
Fuel_Type            1234 non-null object
Transmission         1234 non-null object
Owner_Type           1234 non-null object
Mileage              1234 non-null object
Engine               1224 non-null object
Power                1224 non-null object
Seats                1223 non-null float64
dtypes: float64(1), int64(2), object(7)
memory usage: 96.5+ KB


In [837]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X = LabelEncoder()
combined[:, 0] = labelencoder_X.fit_transform(combined[:, 0])
combined[:, 3] = labelencoder_X.fit_transform(combined[:, 3])
combined[:, 4] = labelencoder_X.fit_transform(combined[:, 4])
combined[:, 5] = labelencoder_X.fit_transform(combined[:, 5])

onehotencoder = OneHotEncoder(categorical_features = [[0],[3],[4],[5]])
combined = onehotencoder.fit_transform(combined).toarray()
# onehotencoder = OneHotEncoder(categorical_features =  [0])
# X = onehotencoder.fit_transform(X).toarray()

TypeError: '(slice(None, None, None), 0)' is an invalid key

In [615]:
df2.isnull().sum()

Location              0
Year                  0
Kilometers_Driven     0
Fuel_Type             0
Transmission          0
Owner_Type            0
Mileage               0
Engine               10
Power                10
Seats                11
dtype: int64

In [616]:
# Cleaning our data
df2['Engine'] = df2['Engine'].str.replace('CC', '')
df2['Power'] = df2['Power'].str.replace('bhp', '')
df2['Mileage'] = df2['Mileage'].str.replace('km/kg', '')
df2['Mileage'] = df2['Mileage'].str.replace('kmpl', '')
df2['Power'] = df2['Power'].str.replace('null', 'NaN')
df2.head()

Location  Year  Kilometers_Driven Fuel_Type Transmission Owner_Type  \
0       Delhi  2014              40929       CNG       Manual      First   
1  Coimbatore  2013              54493    Petrol       Manual     Second   
2      Mumbai  2017              34000    Diesel       Manual      First   
3   Hyderabad  2012             139000    Diesel       Manual      First   
4      Mumbai  2014              29000    Petrol       Manual      First   

  Mileage Engine   Power  Seats  
0  32.26    998    58.2     4.0  
1   24.7    796    47.3     5.0  
2  13.68   2393   147.8     7.0  
3  23.59   1364     NaN     5.0  
4   18.5   1197   82.85     5.0

In [617]:
# Mark empty values as missing or NaN
df2[['Mileage','Engine', 'Power', 'Seats']] = df2[['Mileage','Engine','Power', 'Seats']].replace('', np.NaN)

In [618]:
# Splitting our data into dependent and independent variables
X2 = df2.iloc[:, :11].values
X2[:10]

array([['Delhi', 2014, 40929, 'CNG', 'Manual', 'First', '32.26 ', '998 ',
        '58.2 ', 4.0],
       ['Coimbatore', 2013, 54493, 'Petrol', 'Manual', 'Second', '24.7 ',
        '796 ', '47.3 ', 5.0],
       ['Mumbai', 2017, 34000, 'Diesel', 'Manual', 'First', '13.68 ',
        '2393 ', '147.8 ', 7.0],
       ['Hyderabad', 2012, 139000, 'Diesel', 'Manual', 'First', '23.59 ',
        '1364 ', 'NaN ', 5.0],
       ['Mumbai', 2014, 29000, 'Petrol', 'Manual', 'First', '18.5 ',
        '1197 ', '82.85 ', 5.0],
       ['Coimbatore', 2016, 85609, 'Diesel', 'Manual', 'Second', '16.0 ',
        '2179 ', '140 ', 7.0],
       ['Pune', 2015, 59000, 'Diesel', 'Automatic', 'First', '12.55 ',
        '2982 ', '168.7 ', 7.0],
       ['Jaipur', 2013, 65000, 'Petrol', 'Manual', 'First', '21.1 ',
        '814 ', '55.2 ', 5.0],
       ['Mumbai', 2011, 66000, 'Petrol', 'Manual', 'Second', '17.0 ',
        '1497 ', '118 ', 5.0],
       ['Coimbatore', 2015, 54684, 'Diesel', 'Manual', 'First', '15.1 ',
     

In [619]:
# Replacing missing values with the mean of the columns
from sklearn.preprocessing import Imputer
imputer2 = Imputer(missing_values = 'NaN', strategy = 'mean', axis = 0)
imputer2 = imputer2.fit(X2[:, 6:])
X2[:, 6:] = imputer2.transform(X2[:, 6:])

In [620]:
X2[2]

array(['Mumbai', 2017, 34000, 'Diesel', 'Manual', 'First', 13.68, 2393.0,
       147.8, 7.0], dtype=object)

In [624]:
X2[:, 0] = labelencoder_X.fit_transform(X2[:, 0])
X2[:, 1] = labelencoder_X.fit_transform(X2[:, 1])
X2[:, 3] = labelencoder_X.fit_transform(X2[:, 3])
X2[:, 4] = labelencoder_X.fit_transform(X2[:, 4])
X2[:, 5] = labelencoder_X.fit_transform(X2[:, 5])

onehotencoder2 = OneHotEncoder(categorical_features = [[0],[1],[3],[4],[5]])
X2 = onehotencoder.fit_transform(X2).toarray()

/home/afroz/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [625]:
X2[2]

array([0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 1.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 1.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 1.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       1.000e+00, 1.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 3.400e+04,
       1.368e+01, 2.393e+03, 1.478e+02, 7.000e+00])

In [607]:
y_pred2 = y_pred2.reshape(-1, 1)

In [608]:
model.score(X2, y2)

ValueError: Number of features of the model must match the input. Model n_features is 49 and input n_features is 46 

In [331]:
ls

car_price_results.xlsx  Data_Train.xlsx         Untitled.ipynb
Data_Test.xlsx          Sample_submission.xlsx
